/*////////////////////////////////////////////////
 Script: nw_s0_sunbeam
 Programmer: Keith Soleski
////////////////////////////////////////////////
Evocation [Light]
Level:  Drd 7, Sun 7
Components: V, S, DF
Casting Time:   1 standard action
Range:  60 ft.
Area:   Line from your hand
Duration:   1 round/level or until all beams are exhausted
Saving Throw:   Reflex negates and Reflex half; see text
Spell Resistance:   Yes

For the duration of this spell, you can use a standard action to evoke a dazzling
beam of intense light each round. You can call forth one beam per three caster
levels (maximum six beams at 18th level). The spell ends when its duration runs
out or your allotment of beams is exhausted.

Each creature in the beam is blinded and takes 4d6 points of damage. Any creatures
to which sunlight is harmful or unnatural take double damage. A successful Reflex
save negates the blindness and reduces the damage by half.

An undead creature caught within the beam takes 1d6 points of damage per caster
level (maximum 20d6), or half damage if a Reflex save is successful. In addition,
the beam results in the destruction of any undead creature specifically harmed
by bright light if it fails its save.

The ultraviolet light generated by the spell deals damage to fungi, mold, oozes,
and slimes just as if they were undead creatures
/*///////////////////////////////////////////////
#include "0i_spells"
void main()
{
    // ***********************************************************
    // *************** Set Spell Structure ***********************
    // ***********************************************************
    // Setup the spell in the structured variables, then pass through the SetSpell function.
    Spell.iSubType = SUBTYPE_MAGICAL;
    Spell.iDescriptor = DESC_LIGHT;
    Spell.iAreaShape = SHAPE_SPHERE;
    Spell.fAreaSize = 40.0f;
    Spell.iTargetType = TARGET_TYPE_ALL;
    Spell.iObjectFilter = OBJECT_TYPE_CREATURE;
    Spell.iDurationType = DURATION_TYPE_ROUNDS;
    Spell.iDuration = 1;
    Spell.iDurPerLvl = 1;
    Spell.iSpellResistance = TRUE;
    Spell.iSaveType = SAVING_THROW_TYPE_DIVINE;
    Spell.iDamageType = DAMAGE_TYPE_DIVINE;
    Spell.iImpact = VFX_IMP_SUNSTRIKE;
    Spell.iBeam = VFX_BEAM_HOLY;
    // Setup the spell.
    Spell = SetSpell (Spell);
    // Check to see if we should still fire off the spell.
    if (Spell.iSpellID == STOP_SPELL) return;
    // When making seperate saves vs Spell Resist make sure to get the SaveDC!
    Spell = GetSaveDC (Spell);
    // *******************************************************************
    // ********************** Spell effects ******************************
    // *******************************************************************
    int iRacialType, iBeams;
    string sTag;
    effect eDmg, eRay;
    // Create effects.
    effect eBlind = EffectBlindness ();
    // Create visual effects.
    effect eImpact = EffectVisualEffect (Spell.iImpact);
    effect eDeathImpact = EffectVisualEffect(VFX_IMP_SUNSTRIKE);
    effect eDuration = EffectVisualEffect (VFX_DUR_CESSATE_NEGATIVE);
    // Link effects
    effect eLink = EffectLinkEffects (eBlind, eDuration);
    // Get Number of beams.
    iBeams = Spell.iCasterLevel / 3;
    if (iBeams < 1) iBeams = 1;
    if (iBeams > 6) iBeams = 6;
    //Get the spells beam target(s).
    Spell = GetSpellBeamTarget (Spell);
    // If there are no targets then exit.
    if (!GetIsObjectValid (Spell.oAreaTarget)) return;
    while (iBeams > 0)
    {
        // Remove a beam.
        iBeams --;
        //Fire cast spell at event for the specified target
        SignalEvent (Spell.oAreaTarget, EventSpellCastAt (Spell.oCaster, Spell.iSpellID));
        eRay = EffectBeam (Spell.iBeam, Spell.oBeamEffector, BODY_NODE_HAND);
        DelayCommand (Spell.fDelay, ApplyEffectToObject (DURATION_TYPE_TEMPORARY, eRay, Spell.oAreaTarget, 1.7f));
        // Make resistance check.
        Spell = ResistAndSave (Spell);
        if (!Spell.iSaveResult)
        {
            iRacialType = GetRacialType (Spell.oAreaTarget);
            //Check if the target is an undead
            if (iRacialType == RACIAL_TYPE_UNDEAD || iRacialType == RACIAL_TYPE_OOZE)
            {
                // Damage 1d6 / level (max 20)
                Spell.iModNumOfDice = 1;
                Spell.iModifierDie = 6;
                Spell.iModDicePerLvl = 1;
                Spell.iMaxModNumOfDice = 20;
                Spell.iModifier = 0;
            }
            else
            {
                // Damage 4d6
                Spell.iModNumOfDice = 4;
                Spell.iModifierDie = 6;
                Spell.iModDicePerLvl = 0;
                Spell.iMaxModNumOfDice = 0;
                Spell.iModifier = 0;
            }
            // Get the result for the effect, sets Spell.iResult.
            Spell = GetModifier (Spell);
            if (!SavingThrowWithEffects (SAVING_THROW_REFLEX, Spell.oAreaTarget, Spell.iSaveDC, Spell.iSaveType, Spell.oCaster))
            {
                // They failed the save so destroy any undead harmed by bright light.
                sTag = GetTag (Spell.oAreaTarget);
                if (sTag == "vampire")
                {
                    // Death by damage.
                    Spell.iResult = GetMaxHitPoints (Spell.oAreaTarget) + 10;
                }
                else
                {
                    // Failed save so blind them.
                    DelayCommand (Spell.fDelay, ApplyEffectToObject (Spell.iDurationType, eLink, Spell.oAreaTarget, Spell.fDuration));
                    // Auto fail so we get the correct damage.
                    Spell.iResult = GetReflexAdjustedDamage (Spell.iResult, Spell.oAreaTarget, 100, Spell.iSaveType);
                }
            }
            // Adjust damage for evasion thus why the save is automatically made.
            else Spell.iResult = GetReflexAdjustedDamage (Spell.iResult, Spell.oAreaTarget, 0, Spell.iSaveType);
            if (Spell.iResult > 0)
            {
                eDmg = EffectDamage (Spell.iResult, Spell.iDamageType);
                //Apply the VFX impact and damage effect
                if (sTag == "vampire") DelayCommand (Spell.fDelay + 0.5f, ApplyEffectToObject (DURATION_TYPE_INSTANT, eDeathImpact, Spell.oAreaTarget));
                else DelayCommand (Spell.fDelay + 0.5f, ApplyEffectToObject (DURATION_TYPE_INSTANT, eImpact, Spell.oAreaTarget));
                DelayCommand (Spell.fDelay + 0.5f, ApplyEffectToObject (Spell.iDurationType, eDmg, Spell.oAreaTarget));
            }
        }
        // Sets the beam to start from the caster for each beam.
        Spell.oAreaTarget = Spell.oCaster;
        //Get the spells beam target(s).
        Spell = GetSpellBeamTarget (Spell);
        // We cannot target the caster so check for new target if it happens.
        if (Spell.oAreaTarget == Spell.oCaster) Spell = GetSpellBeamTarget (Spell);
        // If we have found the last target make sure we use all beams so start again.
        if (Spell.oAreaTarget == OBJECT_INVALID) Spell = GetSpellBeamTarget (Spell);
    }
    CleanUpSpell (Spell);
}
